### ISSUE TITLE
provide a docker conf

### ISSUE THREAD

**Issue by gabriel-tessier** [jctt1983/HeadUP#2]
using a virtual box can be helpful especially if you want to test... now I'm stuck with npm that not install correctly on my kubuntu... :cry:

**Comment by gabriel-tessier** [comment]
here some resources: 
https://hub.docker.com/r/tiangolo/uwsgi-nginx-flask/
https://hub.docker.com/_/mysql/
after for the node.js I don't know can you provide more information about I'll try to build one for my fork with elastic!

**Comment by jctt1983** [comment]
Thanks Gabriel, will look into this :)

**Comment by gabriel-tessier** [comment]
Now that it work on my local I will start checking to make a docker compose and publish a ready to run package.
https://docs.docker.com/compose/
May look to heroku to host an example.
And add a screenshot in the readme.

**Comment by gabriel-tessier** [comment]
@jctt1983 
You can check here there's some good example.
https://github.com/tiangolo/uwsgi-nginx-flask-docker

**Comment by jctt1983** [comment]
@gabriel-tessier  Hey Gabriel, I created a docker compose file which integrates different part of the backend. 

I've updated the README, if you have time check it out and let me know if I miss anything. 
Cheers

**Comment by jctt1983** [comment]
@gabriel-tessier  Hopefully we can make it easy to migrate to latest version of python, as there are many flask dependencies that needs to be updated too.

**Comment by gabriel-tessier** [comment]
I'll check later today!

**Comment by jctt1983** [comment]
I finished this issue, finally I got flask socket-io working, so I'm happy that the base config is working. I will close this issue. Then I can focus in Python 3
